# cluster_name is used to group the nodes in a folder within VirtualBox:
cluster_name: Kubernetes Cluster
# All IPs/CIDRs should be private and allowed in /etc/vbox/networks.conf.
network:
  # IPs are simply incremented from the control IP.
  control_ip: 10.0.0.10
  dns_servers:
  - 8.8.8.8
  - 1.1.1.1
  pod_cidr: 172.16.1.0/16
  service_cidr: 172.17.1.0/18
  domain: k8scp
nodes:
  control:
    count: 1
    cpu: 2
    memory: 4096
  workers:
    count: 2
    cpu: 1
    memory: 2048
shared_folders:
  - host_path: ../data
    vm_path: /usr/data    
software:
  box: bento/ubuntu-22.04

