# This config is used in the initial creation of the cluster
# see kubeadm init command
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  bindPort: 6443
nodeRegistration:
  name: "cp1"

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
controlPlaneEndpoint: "k8scp:6443"
networking:
  podSubnet: "172.16.1.0/16"
  serviceSubnet: "172.17.1.0/18"
apiServer:
  extraArgs:
  - name: "bind-address"
    value: "0.0.0.0"
controllerManager:
  extraArgs:
  - name: "bind-address"
    value: "0.0.0.0"
scheduler:
  extraArgs:
  - name: "bind-address"
    value: "0.0.0.0"
etcd:
  local:
    extraArgs:
    - name: "listen-metrics-urls"
      value: "http://0.0.0.0:2381"
# This currently needs to be set manually after the cluster comes up
# to allow Prometheus to gather proxy metrics
# > kubectl edit configmaps -n kube-system kube-proxy
# >>>  metricsBindAddress: 0.0.0.0:10249
# TODO set metricsBindAddress during setup.
#kubeProxy:
#  config:
#    kind: KubeProxyConfiguration
#    apiVersion: kubeproxy.config.k8s.io/v1alpha1
#    metricsBindAddress: "0.0.0.0:10249"  