apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
localAPIEndpoint:
  bindPort: 6443
nodeRegistration:
  name: "cp1"

---
apiVersion: kubeadm.k8s.io/v1beta4
kind: ClusterConfiguration
controlPlaneEndpoint: "k8scp:6443"
networking:
  podSubnet: "172.16.1.0/16"
  serviceSubnet: "172.17.1.0/18"
apiServer:
  extraArgs:
  - name: "bind-address"
    value: "0.0.0.0"
controllerManager:
  extraArgs:
  - name: "bind-address"
    value: "0.0.0.0"
scheduler:
  extraArgs:
  - name: "bind-address"
    value: "0.0.0.0"
